### ISSUE TITLE
Dash is not showing any system stats

### ISSUE THREAD

**Issue by WardsParadox** [afaqurk/linux-dash#302]
The dashboard is not showing any system stats (such as CPU, Memory, etc)
PHP has no disabled functions, safe mode is disabled, and I have restarted the php service.
I have noticed in the Chrome console that angular.min.js is throwing this error:
    `TypeError: Cannot read property '1_min_avg' of undefined
    at Object.scope.loadMetrics.generate (http://localhost:8888/linux-dash/js/modules.js:102:53)
    at http://localhost:8888/linux-dash/js/linuxDash.js:419:48
    at Array.forEach (native)
    at http://localhost:8888/linux-dash/js/linuxDash.js:418:31
    at http://localhost:8888/linux-dash/js/linuxDash.js:60:20
    at http://localhost:8888/linux-dash/js/angular.min.js:111:182
    at k.$eval (http://localhost:8888/linux-dash/js/angular.min.js:125:40)
    at k.$digest (http://localhost:8888/linux-dash/js/angular.min.js:122:127)
    at k.$apply (http://localhost:8888/linux-dash/js/angular.min.js:125:307)
    at m (http://localhost:8888/linux-dash/js/angular.min.js:80:455)`

What can I do to get this running?

**Comment by WardsParadox** [comment]
Realized that this is not compatible with OS X. It's not close enough to Unix to be fully compatible.
