### ISSUE TITLE
Dash seems to be broken on Raspberry Pi 2 B

### ISSUE THREAD

**Issue by mantognini** [afaqurk/linux-dash#328]
Hi,

I've just got my hand on a Raspberry Pi 2 B and decided to install Dash on it as I have on my older Pi B+ model. But instead of flawlessly working as it does on the older model, I got a tonne of error in Chrome console. And basically, every widget is empty, plus the RAM USAGE one is completely missing.

I'm using on both device the current master branch of this repo.

```
3angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20…0filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%09&p2=%09
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=partition%20in%20diskSpaceData&p1=string%3Ap&p2=p
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
angular.min.js:101 TypeError: Cannot read property 'strokeStyle' of undefined
    at linuxDash.js:411
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
21angular.min.js:101 TypeError: Cannot read property 'append' of undefined
    at linuxDash.js:434
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
3angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20…0filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%09&p2=%09
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
3angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=(name%2C%20value)%20in%20tableRows&p1=string%3Ap&p2=p
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
4angular.min.js:101 TypeError: Cannot read property 'append' of undefined
    at linuxDash.js:434
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
5angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20…0filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%09&p2=%09
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=(name%2C%20value)%20in%20tableRows&p1=string%3Ap&p2=p
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
2angular.min.js:101 TypeError: Cannot read property 'strokeStyle' of undefined
    at linuxDash.js:411
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
24angular.min.js:101 TypeError: Cannot read property 'append' of undefined
    at linuxDash.js:434
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
3angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20…0filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%09&p2=%09
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
15angular.min.js:101 TypeError: Cannot read property 'append' of undefined
    at linuxDash.js:434
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=row%20in%20tableRows%20…0filter%3Akeyword%20%7C%20orderBy%3A%20sortByColumn&p1=string%3A%09&p2=%09
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
2angular.min.js:101 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.3.4/ngRepeat/dupes?p0=(name%2C%20value)%20in%20tableRows&p1=string%3Ap&p2=p
    at Error (native)
    at http://rpi2/js/angular.min.js:6:416
    at http://rpi2/js/angular.min.js:234:262
    at Object.fn (http://rpi2/js/angular.min.js:121:305)
    at k.$get.k.$digest (http://rpi2/js/angular.min.js:122:368)
    at k.$get.k.$apply (http://rpi2/js/angular.min.js:125:307)
    at m (http://rpi2/js/angular.min.js:80:455)
    at N (http://rpi2/js/angular.min.js:85:32)
    at XMLHttpRequest.w.onload (http://rpi2/js/angular.min.js:86:69)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76$get.k.$digest @ angular.min.js:123$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86
96angular.min.js:101 TypeError: Cannot read property 'append' of undefined
    at linuxDash.js:434
    at linuxDash.js:60
    at angular.min.js:111
    at k.$get.k.$eval (angular.min.js:125)
    at k.$get.k.$digest (angular.min.js:122)
    at k.$get.k.$apply (angular.min.js:125)
    at m (angular.min.js:80)
    at N (angular.min.js:85)
    at XMLHttpRequest.w.onload (angular.min.js:86)(anonymous function) @ angular.min.js:101$get @ angular.min.js:76(anonymous function) @ angular.min.js:111$get.k.$eval @ angular.min.js:125$get.k.$digest @ angular.min.js:122$get.k.$apply @ angular.min.js:125m @ angular.min.js:80N @ angular.min.js:85w.onload @ angular.min.js:86```

Since I've no idea how those JS things work, let me know if you need more details about anything.

**Comment by afaqurk** [comment]
It looks like the JS part is fine but it is getting empty data. I've seen that error before in situations when the back-end provides empty or no results. 

As a first step of debugging, could you please assure that the back-end for linux dash is working? Perhaps try the General Info endpoint: http://[your-server-address]/server/?module=general_info

**Comment by afaqurk** [comment]
@mantognini : any update?

**Comment by mantognini** [comment]
I just came back from a journey. I'll test it later today. ;)

**Comment by mantognini** [comment]
So on the raspberry that works I get

> { "OS": "3.18.11+", "Hostname": "rpi", "Uptime": " 18 days 7 hours 19 minutes and 54 seconds ", "Server Time": "Wed Sep 2 19:24:52 CEST 2015" }

And on the one that doesn't:

> { "OS": "4.1.6-v7+", "Hostname": "RPI2", "Uptime": " 6 days 2 hours 58 minutes and 8 seconds ", "Server Time": "Wed Sep 2 19:25:03 CEST 2015" }

The only notable difference being the kernel apparently.. Is this a known limitation or should I be looking for more clues elsewhere?

**Comment by afaqurk** [comment]
Hmm. That is not what I expected. The endpoint is working fine. 

As long as you get a JSON response, the back-end is behaving normally. At least, that endpoint is behaving normally. Which means there is another endpoint which is responding with faulty information (duplicates).

Rather than chasing down each, could you please try the following:
* Open up chrome dev tools when on your Linux Dash page
* Go to Networks tab
* reload the page
* look for the first AJAX call that fails (it will be highlighted in red)
* paste the name of the call and it's response (you can get it by clicking on the name)

This will help us see which AJAX call fails first. And hopefully we can fix the issue from there.

Thank you for hanging in there. This will help future devs who are using Linux Dash on Rasberry Pi 2 B.

**Comment by mantognini** [comment]
Well, good news: now it works on both devices. I don't know why but it does. Maybe some conflict with another service running on the device has resolved by itself?

**Comment by afaqurk** [comment]
@mantognini : well, that's good news either way. Enjoy!
