### ISSUE TITLE
 Unhandled 'error' event

### ISSUE THREAD

**Issue by itfanr** [afaqurk/linux-dash#346]
node -v v5.0.0 

```
➜  linux-dash git:(master) node server/
Linux Dash Server Started!
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/home/itfanr/share/repo_git/github.com/afaqurk/linux-dash/server/index.js:9:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

```

Can you help me?

**Comment by itfanr** [comment]
I have kown the reason.It is because I got go app run .Thank you.
