### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by ChimpGamer** [afaqurk/linux-dash#399]
getting error when running node server/

module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/linux-dash/server/index.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by afaqurk** [comment]
You need to run `npm install` to install dependencies first.

Please see the instructions for Node.js Linux Dash server in the Readme https://github.com/afaqurk/linux-dash#nodejs
