### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ChimpGamer** [afaqurk/linux-dash#400]
getting error when running node server/ and i did npm install before
module.js:328
throw err;
^

Error: Cannot find module 'express'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object. (/var/www/html/linux-dash/server/index.js:1:77)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)

**Comment by afaqurk** [comment]
Was there any error output from `npm install`?

I just did a fresh clone, `npm install`, and `sudo node server` and it worked. For that reason, this does not seem like an *issue* with Linux Dash.

If you need general help with getting Linux Dash running, try the [gitter support channel](gitter.im/afaqurk/linux-dash). You can paste any errors you are getting into that chat and I'd be happy to help you debug further.
