### ISSUE TITLE
events.js:141    throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by blub4747** [afaqurk/linux-dash#440]
Hi guys,

I am trying to run linux-dash on my cubietruck  under armbian Ubuntu flavour.
I went for the Node.js path and installed the following packages 
`apt-get install npm

apt-get install node

apt-get install node.js

apt-get install nodejs-legacy`

Finally when I ran the 
node index.js command 
I received the following error msgs

`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Object.<anonymous> (/home/blub/Downloads/linux-dash/app/server/index.js:11:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)`
Can somoneone please tell what is going wrong ?
thx, blub4747

**Comment by blub4747** [comment]
Sorry guys after looking at error msg. I understood that a different webserver was already occupping port 80.
I therefore decided to run linux-dash on port 8080 and it is running fine now.
